version: '3'
services:
  babyfile:
    build:
      context: .
    working_dir: /home/pwn
    container_name: babyfile
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "3157:9999"
    entrypoint: /etc/init.sh
    init: true
    restart: always
