version: '3'
services:
  simplemod:
    build:
      context: .
    working_dir: /home/pwn
    container_name: simplemod
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "7250:9999"
    entrypoint: /etc/init.sh
    init: true
    restart: always
