version: '3'
services:
  lslice:
    build:
      context: .
    working_dir: /home/pwn
    container_name: lslice
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9876:9999"
    entrypoint: /etc/init.sh
    restart: always
