version: '3'
services:
  findflag:
    build:
      context: .
    working_dir: /home/ctf
    container_name: findflag
    restart: always
    environment:
      - FLAG=SECCON{exit_1n_Pyth0n_d0es_n0t_c4ll_exit_sysc4ll}
    ports:
      - "10042:10042"
